[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 90
profile = "black"
# TODO: tox4 config?
# Ref: https://github.com/tox-dev/tox/issues/999

[tool.black]
line-length = 90
exclude = '''
/(
    \.git
  | \.direnv
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | _build
  | __pycache__
  | build
  | dist

  # specific to waybar-check-gmail
  | ^/assets
)/
'''
# Targeting future versions as well so we don't have black reformatting code
# en masse later.
target_version = ["py38", "py310", "py311"]
